import { Facility, FacilityType } from '../types/index.js';

export const mockFacilities: Facility[] = [
  {
    id: 'facility-1',
    name: 'Junnar Sub-Centre',
    type: FacilityType.SUB_CENTRE,
    latitude: 18.78,
    longitude: 73.87,
    district: 'Pune',
    taluka: 'Junnar',
    beds: { total: 6, available: 4, occupied: 2 },
    medicineAvailability: 85,
    specialists: ['General Practitioner'],
    contactPhone: '020-24441111',
    isActive: true,
  },
  {
    id: 'facility-2',
    name: 'Mulshi PHC',
    type: FacilityType.PHC,
    latitude: 18.45,
    longitude: 73.78,
    district: 'Pune',
    taluka: 'Mulshi',
    beds: { total: 12, available: 8, occupied: 4 },
    medicineAvailability: 92,
    specialists: ['General Practitioner', 'Pediatrician'],
    contactPhone: '020-24442222',
    isActive: true,
  },
  {
    id: 'facility-3',
    name: 'Velhe PHC',
    type: FacilityType.PHC,
    latitude: 18.42,
    longitude: 73.65,
    district: 'Pune',
    taluka: 'Velhe',
    beds: { total: 15, available: 10, occupied: 5 },
    medicineAvailability: 78,
    specialists: ['General Practitioner', 'Gynecologist'],
    contactPhone: '020-24443333',
    isActive: true,
  },
  {
    id: 'facility-4',
    name: 'Ambegaon PHC',
    type: FacilityType.PHC,
    latitude: 18.95,
    longitude: 73.85,
    district: 'Pune',
    taluka: 'Ambegaon',
    beds: { total: 10, available: 7, occupied: 3 },
    medicineAvailability: 88,
    specialists: ['General Practitioner'],
    contactPhone: '020-24444444',
    isActive: true,
  },
  {
    id: 'facility-5',
    name: 'Bhor PHC',
    type: FacilityType.PHC,
    latitude: 18.15,
    longitude: 73.95,
    district: 'Pune',
    taluka: 'Bhor',
    beds: { total: 12, available: 9, occupied: 3 },
    medicineAvailability: 90,
    specialists: ['General Practitioner', 'Ayurvedic'],
    contactPhone: '020-24445555',
    isActive: true,
  },
  {
    id: 'facility-6',
    name: 'Khed CHC',
    type: FacilityType.CHC,
    latitude: 18.35,
    longitude: 73.85,
    district: 'Pune',
    taluka: 'Khed',
    beds: { total: 30, available: 22, occupied: 8 },
    medicineAvailability: 95,
    specialists: ['General Practitioner', 'Surgeon', 'Physician', 'Gynecologist'],
    contactPhone: '020-24446666',
    isActive: true,
  },
  {
    id: 'facility-7',
    name: 'Shirur CHC',
    type: FacilityType.CHC,
    latitude: 18.65,
    longitude: 74.00,
    district: 'Pune',
    taluka: 'Shirur',
    beds: { total: 25, available: 18, occupied: 7 },
    medicineAvailability: 91,
    specialists: ['General Practitioner', 'Surgeon', 'Pediatrician'],
    contactPhone: '020-24447777',
    isActive: true,
  },
  {
    id: 'facility-8',
    name: 'Sassoon District Hospital Pune',
    type: FacilityType.DISTRICT_HOSPITAL,
    latitude: 18.52,
    longitude: 73.87,
    district: 'Pune',
    taluka: 'Pune City',
    beds: { total: 500, available: 350, occupied: 150 },
    medicineAvailability: 98,
    specialists: [
      'Cardiologist',
      'Neurologist',
      'Surgeon',
      'Physician',
      'Gynecologist',
      'Pediatrician',
      'Orthopedic',
      'ENT',
    ],
    contactPhone: '020-24440000',
    isActive: true,
  },
  {
    id: 'facility-9',
    name: 'Alandi Sub-Centre',
    type: FacilityType.SUB_CENTRE,
    latitude: 18.68,
    longitude: 73.92,
    district: 'Pune',
    taluka: 'Pune',
    beds: { total: 4, available: 3, occupied: 1 },
    medicineAvailability: 80,
    specialists: ['General Practitioner'],
    contactPhone: '020-24448888',
    isActive: true,
  },
  {
    id: 'facility-10',
    name: 'Maval Sub-Centre',
    type: FacilityType.SUB_CENTRE,
    latitude: 18.55,
    longitude: 73.72,
    district: 'Pune',
    taluka: 'Maval',
    beds: { total: 6, available: 5, occupied: 1 },
    medicineAvailability: 75,
    specialists: ['General Practitioner', 'AYUSH'],
    contactPhone: '020-24449999',
    isActive: true,
  },
];
