const FIRST_AID_PROTOCOLS: Record<string, string[]> = {
  'cardiac_arrest': [
    'Call for help immediately — do not leave patient alone',
    'Check if patient is breathing — look, listen, feel for 10 seconds',
    'If not breathing: Begin CPR — 30 chest compressions, then 2 rescue breaths',
    'Continue CPR until help arrives — do NOT stop',
    'If available: Use AED (Automated External Defibrillator)',
    'Keep patient flat on a firm surface',
    'Do NOT give water or food',
  ],
  'severe_bleeding': [
    'Apply direct pressure to the wound using a clean cloth',
    'Do NOT remove the cloth even if blood soaks through — add more layers',
    'If limb: Elevate the injured limb above heart level',
    'Apply pressure bandage firmly but not too tight',
    'If bleeding won\'t stop: Apply tourniquet 5-7 cm above the wound',
    'Note the time tourniquet was applied',
    'Keep patient warm — cover with blanket',
    'Do NOT give water if abdominal injury suspected',
  ],
  'snakebite': [
    'Keep patient CALM and STILL — movement spreads venom faster',
    'Immobilize the bitten limb with a splint — keep below heart level',
    'Remove rings, watches, tight clothing near the bite',
    'Do NOT cut the wound or try to suck out venom',
    'Do NOT apply ice or tourniquet',
    'Do NOT give alcohol or painkillers',
    'Mark the edge of swelling with pen and note the time',
    'If possible, take a photo of the snake (for identification)',
    'Transport to hospital with anti-venom facility URGENTLY',
  ],
  'difficulty_breathing': [
    'Sit patient upright — do NOT lay them flat',
    'Loosen any tight clothing around neck and chest',
    'If asthma patient: Help them use their inhaler (2 puffs)',
    'Open windows for fresh air',
    'If SpO2 monitor available: Check oxygen saturation',
    'If SpO2 below 92%: Administer oxygen if available',
    'Count respiratory rate — report to doctor',
    'Keep patient calm — anxiety worsens breathing difficulty',
  ],
  'unconscious': [
    'Check if patient responds to voice or gentle shake',
    'Check breathing — look, listen, feel for 10 seconds',
    'If breathing: Place in recovery position (left lateral)',
    'If NOT breathing: Start CPR immediately',
    'Do NOT give anything by mouth',
    'Check for injuries — head, neck, spine',
    'Protect head — place soft support',
    'Monitor breathing continuously until help arrives',
  ],
  'poisoning': [
    'Identify the poison if possible — keep the container/bottle',
    'Call Poison Control: 1800-116-117',
    'Do NOT induce vomiting unless specifically told by doctor',
    'If poison on skin: Remove contaminated clothing, wash with water for 15-20 min',
    'If poison in eyes: Flush with clean water for 15-20 min',
    'If inhaled: Move to fresh air immediately',
    'If conscious: Give small sips of water or milk (ONLY if advised)',
    'Note: What was consumed, how much, when',
  ],
  'pregnancy_emergency': [
    'Keep mother in left lateral position',
    'Check for bleeding — note amount and color',
    'Monitor fetal movement — ask mother if baby is moving',
    'Check blood pressure if equipment available',
    'Do NOT give any medication without doctor\'s advice',
    'Keep mother warm and calm',
    'If active labor: Do NOT try to delay delivery',
    'If cord is visible: Do NOT push it back — support and keep moist',
    'Transport to hospital with obstetric facility IMMEDIATELY',
  ],
  'severe_burns': [
    'Remove patient from heat source — ensure YOUR safety first',
    'Cool burn with clean running water for 20 minutes',
    'Do NOT use ice, butter, toothpaste, or any home remedies',
    'Remove jewelry and clothing near the burn (if not stuck)',
    'Cover with clean, non-stick dressing or clean cloth',
    'Do NOT burst blisters',
    'For chemical burns: Remove contaminated clothing, flush with water',
    'Give small sips of water if patient is conscious',
    'Monitor for signs of shock: pale skin, rapid pulse, confusion',
  ],
};

const DEFAULT_FIRST_AID = [
  'Keep patient comfortable and calm',
  'Monitor vital signs: pulse, breathing, consciousness',
  'Do NOT give any medication without doctor\'s advice',
  'Keep patient warm — cover with blanket',
  'Note all symptoms and their onset time',
  'Prepare for transport to nearest health facility',
];

export function getFirstAidSteps(condition: string): string[] {
  return FIRST_AID_PROTOCOLS[condition] || DEFAULT_FIRST_AID;
}
